# app/utils/token_helpers.py
# ───────────────────────────
# Invitation token generation and verification using itsdangerous.
#
# How it works
# ────────────
# itsdangerous.URLSafeTimedSerializer:
#   • Takes a payload dict  →  produces a URL-safe base64 string
#   • Signs it with the app's SECRET_KEY using HMAC-SHA1
#   • Embeds a timestamp so we can enforce time-based expiry
#   • Verifying a tampered or expired token raises an exception
#
# The resulting token looks like:
#   eyJlbWFpbCI6ICJhZG1pbkBleGFtcGxlLmNvbSJ9.ZdXnTg.abc123...
#   └───────────── payload (base64) ─────────────┘└──ts──┘└─sig─┘
#
# Why a SALT?
# ───────────
# The salt ("invitation-salt") is a domain-separation string.
# If other parts of the app also use itsdangerous (e.g. for password
# resets), a token generated for one purpose cannot be replayed for
# another — even though they share the same SECRET_KEY.
#
# Database vs. token
# ──────────────────
# We store a row in invitation_tokens for two reasons:
#   1. We can mark is_used=True after registration so tokens are
#      single-use (itsdangerous alone cannot enforce this).
#   2. Admins can see which invitations are pending / expired.

from flask import current_app
from itsdangerous import URLSafeTimedSerializer, SignatureExpired, BadSignature


# Domain-separation salt — must match between generate and verify calls
_SALT = "invitation-salt"


def generate_invitation_token(email: str, role: str, store_id: int | None) -> str:
    """
    Create a signed, URL-safe token encoding the invitee's details.

    This token is embedded in the invitation link that gets emailed:
        https://app.example.com/register?token=<token>

    Parameters
    ----------
    email    : str       – the recipient's email address
    role     : str       – "admin" or "clerk"
    store_id : int|None  – the store the new user will join

    Returns
    -------
    str
        A URL-safe signed token string.

    Example
    -------
    >>> with app.app_context():
    ...     token = generate_invitation_token("jane@example.com", "clerk", 1)
    ...     isinstance(token, str)
    True
    """
    serializer = URLSafeTimedSerializer(current_app.config["SECRET_KEY"])

    # The payload is embedded in the token (base64, not encrypted —
    # do NOT put sensitive data here beyond what is needed for registration)
    payload = {
        "email":    email,
        "role":     role,
        "store_id": store_id,
    }

    return serializer.dumps(payload, salt=_SALT)


def verify_invitation_token(token: str, max_age: int | None = None) -> dict | None:
    """
    Decode and verify a signed invitation token.

    Checks:
      • Cryptographic signature (was this token generated by our app?)
      • Timestamp (is it still within max_age seconds of creation?)

    Does NOT check:
      • Whether the token has already been used (is_used flag)
      • Whether the email already has an account
    Those checks are done in the route handler using the database.

    Parameters
    ----------
    token   : str       – the raw token string from the URL query param
    max_age : int|None  – seconds until expiry; defaults to the
                          INVITATION_TOKEN_EXPIRES config value (24 h)

    Returns
    -------
    dict
        The decoded payload: {"email": ..., "role": ..., "store_id": ...}
        if the token is valid.
    None
        If the token is expired, tampered with, or otherwise invalid.

    Example
    -------
    >>> with app.app_context():
    ...     token = generate_invitation_token("jane@example.com", "clerk", 1)
    ...     payload = verify_invitation_token(token)
    ...     payload["email"]
    'jane@example.com'
    """
    if max_age is None:
        # Fall back to the config value so tests can override it easily
        max_age = current_app.config.get("INVITATION_TOKEN_EXPIRES", 86400)

    serializer = URLSafeTimedSerializer(current_app.config["SECRET_KEY"])

    try:
        payload = serializer.loads(token, salt=_SALT, max_age=max_age)
        return payload

    except SignatureExpired:
        # Token was valid but the time window has passed
        return None

    except BadSignature:
        # Token was tampered with or generated with a different SECRET_KEY
        return None